### ISSUE TITLE
throwException!T.original returns different Type in 0.14 alpha

### ISSUE THREAD

**Issue by skruppy** [gedaiu/fluent-asserts#97]
The following example compiles and behaves as expected in Version 0.13.0 but fails to compile with 0.14.0-alpha.8 (return type of `original` is `Expect`, not the expected `SomeException`)
```D
import std.stdio;
import fluent.asserts;



void main() {
	writeln("Edit source/app.d to start your project.");
}

class SomeException : Exception {
	this(string msg, string file = __FILE__, size_t line = __LINE__) {
		super(msg, file, line);
	}
}

unittest {
	SomeException ex = ({throw new SomeException("msg");}).should.throwException!SomeException.original;
}
```

**Comment by gedaiu** [comment]
does `thrown` works for you?

```d
unittest {
	Throwable ex = ({throw new SomeException("msg");}).should.throwException!SomeException.thrown;
}
```

**Comment by skruppy** [comment]
Kind of. I actually need the correct type, which is not a big problem since I can simply use `cast(SomeException)`. This is my current workaround. But I guess it's a regression bug.

Things I don't understand:
 * `throwException` does not return `ThrowableProxy` as said [here](https://github.com/gedaiu/fluent-asserts/blob/52427ed7f7b77f5c198050612b0edde7b939b813/api/callable.md#throw-exception)
 * The [implementation](https://github.com/gedaiu/fluent-asserts/blob/52427ed7f7b77f5c198050612b0edde7b939b813/source/fluentasserts/core/base.d#L377) in `ThrowableProxy` of `original` seems to be right, but as said before it also seems not to be used but I also does not find another implementation. ... I'm really confused :)

**Comment by gedaiu** [comment]
I had to change the library structs to have a more modern interface like chai from js. This helps on allowing other devs to bind their custom checks to the lib. If you want to check the latest work please have a look at the master branch.

If you really need the prev behavior i’ll need to see how can I do this without adding more templates… because I also aim to improve the compilation speed with this new version.

Unfortunately the docs are outdated. I did not have much time to focus on this project and the current version is still an alpha. I’ll make a beta release once I can get some focus time on it.

**Comment by skruppy** [comment]
Oh OK. The API change is then probably what confused me then. Since there is a workaround and this change was intended and hence not a regression, I'll close this issue (even if `original` was convenient :wink:).

Maybe it's a good idea to mark `original` or `ThrowableProxy` some day with [`deprecated("Hint to new API")`](https://dlang.org/spec/attribute.html#deprecated).

Thanks for all your great work :heart:
